### ISSUE TITLE
noisy counts vs. counts of noise?

### ISSUE THREAD

**Issue by mccalluc** [opendp/dp-creator-ii#100]
Right now, the sample code bins the values, and then applies noise to the counts. An alternative would be to apply noise to the values before binning. Is either clearly better or worse? The approach does influence what "contributions" means: is it the maximum number of values, or the maximum number of bins that an individual can contribute to? Since an individual can't contribute to more bins than they have values, there is a bound, but it might be inefficient.

**Comment by Shoeboxam** [comment]
Good question! There's a tendency where the later in the data pipeline that noise/randomization happens, the better your utility gets. This is why, on the same data, typically local-dp has more noise than shuffle-dp has more noise than central-dp. However, what you get from it is that since you're adding noise earlier in the pipeline, you might be able to apply the noise locally instead before collecting the data, resulting in a lower trust requirement from the user (satisfying local or shuffle dp instead of central).

In local dp, we typically assume an individual could completely change their answer, without bound. If you clamp their scalar response to a range (a, b), then you could claim their sensitivity is b - a, and privatize the clamped scalar with the laplace or gaussian mechanism. Note that in order to avoid introducing bias, you'll want your bounds a and b to be the lower and upper bin edges, which will be pretty wide, resulting in a lot of noise, as is typical in local-dp. While this would satisfy privacy, you might get better utility by using randomized response to pick one of the k bins, biasing toward the bin the user was in.

It might be possible to analyze under central-DP as well, but you have to consider the randomization and aggregation together, which could make the analysis tricky...

**Comment by mccalluc** [comment]
Confirmed this morning with Mike that adding noise to the counts makes sense in this context, and that an additional note on the unit of privacy in the generated notebook shouldn't be necessary. (I had been a little confused at the start of this process and ended up with this approach because it was easy, rather than correct... but it is also correct.) Closing.
