### ISSUE TITLE
Initial characters in list of CSV columns look strange

### ISSUE THREAD

**Issue by ekraffmiller** [opendp/dp-creator-ii#72]
When uploading these files, check the first characters displayed:
[teacher_survey.csv](https://github.com/user-attachments/files/17439469/teacher_survey.csv)
[voter_validation_lwd.csv](https://github.com/user-attachments/files/17439471/voter_validation_lwd.csv)

**Comment by mccalluc** [comment]
```
>>> from pathlib import Path
>>> p = Path('/Users/chuckmccallum/Downloads/teacher_survey.csv')
>>> t = p.read_text()
>>> t[0:10]
'\ufeffsex,age,m'
```
`FEFF` if the byte-order-mark. It could be safely stripped (byte-order isn't an issue for utf-8), or it can be read correctly if encoding is `utf-8-sig`, but what happens when this file is read by polars?
```
>>> import polars as pl
>>> lf = pl.scan_csv('/Users/chuckmccallum/Downloads/teacher_survey.csv')
>>> lf.collect().columns
['sex', 'age', 'maritalstatus', 'Havingchild', 'highesteducationlevel', 'sourceofstress', 'smoking', 'optimism', 'lifesattisfaction', 'selfesteem']
```
Looks fine!

Could we specify the encoding when reading without any ill effects if there isn't a BOM?
```
>>> with open("dp_creator_ii/tests/fixtures/fake.csv", newline="", encoding="utf-8-sig") as csv_handle:
...     reader = csv.DictReader(csv_handle)
...     print(reader.fieldnames)
...
['student_id', 'class_year', 'assignment_type', 'grade']
```
Yes!
- Filed #79


Looking at the second file:
```
"","V201","V207","V208",...
"2",1.40380223452636,1943,...
"4",0.709774009439292,1939,...
```
The first column has an empty string for the header. I guess that's ok: we should make sure the UI still works if the column header is an empty string.
- filed #80
